# Generated by Django 6.0.4 on 2026-04-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile_solicitud_vendedor_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
