# Generated by Django 6.0.4 on 2026-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_profile_nombre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='solicitud_vendedor',
        ),
        migrations.AddField(
            model_name='profile',
            name='solicita_vendedor',
            field=models.BooleanField(default=False, verbose_name='Solicita ser vendedor'),
        ),
    ]
